# config.yaml

# 1. DATASET CONFIGURATION
dataset:
  mode: "metr-la"             # Switch between "dummy", "semi-real", and "metr-la"
  filepath: "data/traffic_data.npz"
  
  # Configuration for generate_dataset.py
  semi-real:
    num_days: 90
    q: 288
    
  # Configuration for METR-LA dataset
  metr-la:
    data_path: "raw_data/metr-la.h5"
    adj_path: "raw_data/adj_mx.pkl"
    # Split ratios
    train_split: 0.7
    val_split: 0.1
    # Test split is the remainder (0.2)

# 2. DATA CONFIGURATION (must match METR-LA)
data:
  num_nodes: 207           # METR-LA has 207 sensors
  num_features: 3          # We will use speed and expand it to 3 features
  Th: 12
  Td: 12
  Tw: 12
  Tp: 12

# 3. MODEL CONFIGURATION
model:
  num_st_blocks: 2
  K: 3

# 4. TRAINING CONFIGURATION
training:
  device: "cuda"
  batch_size: 16
  epochs: 100
  learning_rate: 0.001

# 5. CHECKPOINT CONFIGURATION
checkpoint:
  path: "checkpoints/"
  filename: "best_model.pth" # Save the best model based on validation loss