# config.yaml

# 1. DATASET CONFIGURATION
dataset:
  mode: "real"             # Switch between "dummy" and "real"
  filepath: "data/traffic_data.npz"
  # Configuration for generate_dataset.py
  generation:
    num_days: 90           # Generate 3 months of data
    q: 288                 # Samples per day (24 * 60 / 5 minutes = 288)

# 2. DATA CONFIGURATION (used by the model)
data:
  num_nodes: 207
  num_features: 3
  Th: 12
  Td: 12
  Tw: 12
  Tp: 12

# 3. MODEL CONFIGURATION
model:
  num_st_blocks: 2
  K: 3

# 4. TRAINING CONFIGURATION
training:
  device: "cuda"
  batch_size: 16
  epochs: 100
  learning_rate: 0.001

# 5. CHECKPOINT CONFIGURATION
checkpoint:
  path: "checkpoints/"
  filename: "last_checkpoint.pth"